### PR TITLE
Rect and quad

### PR DESCRIPTION
**Pull request by KevinDoughty**
I've implemented the DOMRect and DOMQuad classes, but there are no tests yet. I copied your coding style from DOMPoint. I used https://www.w3.org/TR/geometry-1/ instead of https://drafts.fxtf.org/geometry/ but they look identical to me.

### CODE REVIEW

**Comment by jorisw** [comment]
@trusktr Please review this

**Comment by KevinDoughty** [comment]
I only vaguely remember doing this, I think my interest was in layout animations. If the code is insufficient let me know what should be done to correct it. I'm unsure what should be done for tests.

**Comment by trusktr** [comment]
I totally forgot about this! Let's just get this in and get it moving. After this is merged, it would be nice to get rid of the WeakMap private implementation and just use the new `#private` syntax. I'm not going to check that this matches the spec exactly, but if it doesn't, we can update it.

Although all browsers support `DOMMatrix` and related classes these days, it would still be useful to have this complete so that it can serve as polyfill in environments like Node.js, Deno, etc. Also maybe it can be an example for Winter CG which is standardizing web APIs across JavaScript runtimes.

Hmm, also I wonder what other DOM polyfills look like nowadays? For example do undom, jsdom, happydom, etc, have versions of this now?

**Comment by KevinDoughty** [comment]
Apologies but I have to rescind my offer to keep working on this. I've wiped my laptop and will not be reinstalling Node in the foreseeable future

**Comment by trusktr** [comment]
Oh that's ok, no worries at all, and that is never the expectation with free contributions to free open source software. :) Thanks for the contribution!

**Pull request merged**
